/* PITWALL V4.2 — original circuit history and real, time-limited event forecasts.
   Builds on V4.1; all career state and storage keys are unchanged. */
'use strict';
const V42_CIRCUITS={
 'Australia':{name:'Albert Park Grand Prix Circuit',opened:'1996 (F1)',wiki:'Albert_Park_Circuit',intro:'Melbourne’s Albert Park hosted its first Formula 1 Australian Grand Prix in 1996, following the race’s move from Adelaide. Its park roads are temporarily transformed into a rapid street-style circuit each race weekend.',moments:['1996: Albert Park hosts its first World Championship Grand Prix, with Damon Hill winning.','The circuit combines fast corners with the distinctive setting of a lake and public park.','Layout and safety changes over the years have made the modern circuit notably quicker.']},
 'China':{name:'Shanghai International Circuit',opened:'2004',wiki:'Shanghai_International_Circuit',intro:'Designed by Hermann Tilke, Shanghai made its Formula 1 debut in 2004. The layout is inspired by the Chinese character shang and features a long, demanding opening corner complex.',moments:['2004: Rubens Barrichello wins the circuit’s inaugural F1 race.','2006: Michael Schumacher takes his final Formula 1 victory here.','Its huge back straight rewards powerful acceleration and creates overtaking opportunities.']},
 'Japan':{name:'Suzuka International Racing Course',opened:'1987 (F1)',wiki:'Suzuka_International_Racing_Course',intro:'Originally built as a Honda test track in 1962, Suzuka entered the Formula 1 calendar in 1987. Its rare figure-eight configuration and linked high-speed corners have made it a favourite among drivers.',moments:['1988 and 1989: Ayrton Senna and Alain Prost’s title battles provide defining moments.','130R, the Esses and Spoon Corner test precision and commitment.','Suzuka has frequently been a stage for World Championship deciders.']},
 'Bahrain':{name:'Bahrain International Circuit',opened:'2004',wiki:'Bahrain_International_Circuit',intro:'The desert venue at Sakhir became the first Formula 1 World Championship circuit in the Middle East in 2004. Its heavy-braking zones and night-time racing make tyre management particularly important.',moments:['2004: Michael Schumacher wins the inaugural Bahrain Grand Prix.','2014: Bahrain stages its first Formula 1 night race, featuring a Mercedes duel.','The combination of abrasive asphalt and sweeping corners makes strategy crucial.']},
 'Saudi Arabia':{name:'Jeddah Corniche Circuit',opened:'2021',wiki:'Jeddah_Corniche_Circuit',intro:'Jeddah’s waterfront street circuit debuted in Formula 1 in 2021. Its sweeping bends, close walls and high average speeds set it apart from many other temporary tracks.',moments:['2021: The venue makes its World Championship debut beside the Red Sea.','A succession of fast corners requires confidence, accuracy and careful race control.','The night-race setting makes the track especially distinctive.']},
 'Miami':{name:'Miami International Autodrome',opened:'2022',wiki:'Miami_International_Autodrome',intro:'Miami joined Formula 1 in 2022 with a temporary circuit constructed around Hard Rock Stadium. It combines long straights, slow complexes and the atmosphere of a major American sporting event.',moments:['2022: Max Verstappen wins the first Miami Grand Prix.','2024: Lando Norris records his first Formula 1 Grand Prix victory here.','The purpose-built temporary layout returns the area to other uses between race meetings.']},
 'Canada':{name:'Circuit Gilles-Villeneuve',opened:'1978 (F1)',wiki:'Circuit_Gilles_Villeneuve',intro:'Montreal’s circuit opened to Formula 1 in 1978 on Île Notre-Dame. Named in honour of Canadian driver Gilles Villeneuve, it features long straights broken by quick chicanes and close barriers.',moments:['1978: Gilles Villeneuve takes his first Grand Prix win at the inaugural Montreal race.','2011: Jenson Button wins a dramatic rain-interrupted Canadian Grand Prix.','The final-corner Wall of Champions is among F1’s most recognisable landmarks.']},
 'Monaco':{name:'Circuit de Monaco',opened:'1929 (Grand Prix)',wiki:'Circuit_de_Monaco',intro:'Monaco’s narrow streets have hosted Grand Prix racing since 1929 and featured in the first Formula 1 World Championship in 1950. Precision matters more than outright speed around its famous harbour setting.',moments:['1929: William Grover-Williams wins the first Monaco Grand Prix.','1984: Ayrton Senna makes his mark during a rain-soaked race.','Sainte Dévote, the tunnel and the harbour section are historic features of the course.']},
 'Barcelona-Catalunya':{name:'Circuit de Barcelona-Catalunya',opened:'1991 (F1)',wiki:'Circuit_de_Barcelona-Catalunya',intro:'The Montmeló circuit has welcomed Formula 1 since 1991. A mix of fast, medium and slow corners long made it a benchmark for teams testing balance and aerodynamic performance.',moments:['1991: The circuit hosts its first Spanish Grand Prix.','1996: Michael Schumacher wins his first race for Ferrari in wet conditions.','The sweeping final sector has been revised over time to improve the racing.']},
 'Austria':{name:'Red Bull Ring',opened:'1970 (original circuit)',wiki:'Red_Bull_Ring',intro:'The Styrian hills have hosted several generations of Formula 1 circuit. Originally the Österreichring, the venue was rebuilt as the A1-Ring in 1997 and returned as the Red Bull Ring in 2014.',moments:['1970: The Österreichring joins the F1 calendar.','1997: The rebuilt A1-Ring hosts its first Austrian Grand Prix.','2014: Formula 1 returns after a decade away from the venue.']},
 'Great Britain':{name:'Silverstone Circuit',opened:'1950 (World Championship)',wiki:'Silverstone_Circuit',intro:'Built on a former Royal Air Force airfield, Silverstone hosted the very first Formula 1 World Championship race in 1950. Its rapid corners have helped shape the history of British motor racing.',moments:['1950: Giuseppe Farina wins the inaugural F1 World Championship race.','Copse, Maggotts, Becketts and Chapel are celebrated high-speed sequences.','The circuit has evolved substantially while retaining its fast character.']},
 'Belgium':{name:'Circuit de Spa-Francorchamps',opened:'1950 (World Championship)',wiki:'Circuit_de_Spa-Francorchamps',intro:'Spa winds through Belgium’s Ardennes forest and has been part of the World Championship since its opening season in 1950. Today’s circuit is shorter than the original road course but remains one of F1’s longest.',moments:['1950: Spa appears in the inaugural Formula 1 World Championship calendar.','Eau Rouge–Raidillon and Blanchimont are legendary high-speed sections.','Rapidly changing Ardennes weather has produced unforgettable races.']},
 'Hungary':{name:'Hungaroring',opened:'1986',wiki:'Hungaroring',intro:'The Hungaroring near Budapest brought Formula 1 behind the Iron Curtain in 1986. Its winding layout has historically made qualifying and well-timed pit strategy especially important.',moments:['1986: Nelson Piquet wins the first Hungarian Grand Prix at this circuit.','1997: Damon Hill nearly secures an unexpected victory for Arrows.','2021: Esteban Ocon celebrates his first Formula 1 win here.']},
 'Netherlands':{name:'Circuit Zandvoort',opened:'1952 (World Championship)',wiki:'Circuit_Zandvoort',intro:'Set among dunes beside the North Sea, Zandvoort has held Formula 1 championship races since 1952. It returned to the calendar in 2021 with dramatic banking added to its flowing layout.',moments:['1952: Alberto Ascari wins the first Dutch World Championship Grand Prix.','2021: Formula 1 returns to Zandvoort after more than three decades.','The steeply banked final corner is a signature feature of the modern track.']},
 'Italy':{name:'Autodromo Nazionale Monza',opened:'1922 (circuit)',wiki:'Monza_Circuit',intro:'Built in 1922, Monza is one of the world’s oldest permanent racing circuits and an F1 venue since 1950. Its long straights and historic setting have earned it the nickname Temple of Speed.',moments:['1950: Monza helps shape the first World Championship season.','The old banked circuit remains visible as a reminder of its past.','The passionate tifosi make the Italian Grand Prix especially atmospheric.']},
 'Spain':{name:'Madring',opened:'2026 (F1 debut)',wiki:'Madrid_Grand_Prix',intro:'Madrid joins the 2026 Formula 1 season with a new semi-permanent circuit around the IFEMA exhibition area. Unlike established venues, it has only just begun writing its modern F1 history.',moments:['2026: Planned World Championship debut for the new Madrid venue.','The design combines urban sections with purpose-built stretches.','Its first Grand Prix will establish the track’s early racing milestones.']},
 'Azerbaijan':{name:'Baku City Circuit',opened:'2016 (F1)',wiki:'Baku_City_Circuit',intro:'Baku’s street circuit first hosted Formula 1 as the European Grand Prix in 2016 and became the Azerbaijan Grand Prix venue in 2017. Its unique mix of a medieval old-town section and an extremely long straight makes every lap challenging.',moments:['2016: The World Championship races in Baku for the first time.','2017: Daniel Ricciardo wins a chaotic inaugural Azerbaijan Grand Prix.','The narrow castle section is one of the tightest sequences on the calendar.']},
 'Singapore':{name:'Marina Bay Street Circuit',opened:'2008',wiki:'Marina_Bay_Street_Circuit',intro:'Marina Bay hosted Formula 1’s first night-time World Championship race in 2008. The humid, brightly lit street circuit is physically demanding and has changed layout several times over the years.',moments:['2008: Fernando Alonso wins the first Singapore Grand Prix.','The race is famous for heat, close barriers and frequent interruptions.','A revised layout introduced in 2023 removed several slow corners.']},
 'United States':{name:'Circuit of the Americas',opened:'2012',wiki:'Circuit_of_the_Americas',intro:'Circuit of the Americas near Austin was built specifically to host Formula 1 and debuted in 2012. Its steep first corner, flowing Esses and large elevation changes draw inspiration from classic racing venues.',moments:['2012: Lewis Hamilton wins the inaugural United States Grand Prix at COTA.','2015: Hamilton secures his third drivers’ championship at this circuit.','The uphill run to Turn 1 is one of the track’s trademark sights.']},
 'Mexico':{name:'Autódromo Hermanos Rodríguez',opened:'1963 (World Championship)',wiki:'Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez',intro:'Mexico City’s high-altitude circuit first hosted Formula 1 in 1963. Renamed after racing brothers Ricardo and Pedro Rodríguez, it features a distinctive stadium section.',moments:['1963: Jim Clark wins the first championship Mexican Grand Prix at the circuit.','2015: Formula 1 returns after a 23-year absence.','Thin air at high altitude challenges cooling and aerodynamic performance.']},
 'Brazil':{name:'Autódromo José Carlos Pace (Interlagos)',opened:'1973 (F1)',wiki:'Interlagos_Circuit',intro:'Interlagos in São Paulo hosted its first World Championship race in 1973. Its undulating anti-clockwise layout, passionate spectators and unpredictable weather have created many title-defining moments.',moments:['1973: Emerson Fittipaldi wins the circuit’s first championship Brazilian Grand Prix.','2008: Lewis Hamilton clinches his first world title on the final lap.','The Senna S turns and long climb to the finish are signature sections.']},
 'São Paulo':{name:'Autódromo José Carlos Pace (Interlagos)',opened:'1973 (F1)',wiki:'Interlagos_Circuit',intro:'Interlagos in São Paulo has been a Formula 1 venue since 1973. Its anti-clockwise circuit, elevation changes and volatile weather make it a classic season highlight.',moments:['1973: Brazilian hero Emerson Fittipaldi wins the first championship race held here.','2008: The dramatic championship conclusion is decided on the final lap.','The Senna S and uphill run to the line are iconic elements.']},
 'Las Vegas':{name:'Las Vegas Strip Circuit',opened:'2023',wiki:'Las_Vegas_Strip_Circuit',intro:'Las Vegas returned to the Formula 1 calendar in 2023 with a night-time street circuit taking in part of the famous Strip. It is distinct from the Caesars Palace races held in the city in the early 1980s.',moments:['2023: Max Verstappen wins the first race on the Strip circuit.','Long straights and cool evening temperatures affect tyre preparation.','The event places racing against the illuminated Las Vegas skyline.']},
 'Qatar':{name:'Lusail International Circuit',opened:'2021 (F1)',wiki:'Lusail_International_Circuit',intro:'Originally built for motorcycle racing, Lusail hosted its first Formula 1 World Championship race in 2021. Its fast flowing turns, night lighting and desert setting create a demanding challenge.',moments:['2021: Lewis Hamilton wins Formula 1’s first Qatar Grand Prix.','High-speed cornering places heavy loads on the tyres.','The venue returned after a break in 2022 and now hosts regular Grand Prix weekends.']},
 'Abu Dhabi':{name:'Yas Marina Circuit',opened:'2009',wiki:'Yas_Marina_Circuit',intro:'Yas Marina on Yas Island debuted in the World Championship in 2009. Its floodlit twilight-to-night races have made it a familiar season finale, and the layout was revised in 2021 to promote better racing.',moments:['2009: Sebastian Vettel wins the first Abu Dhabi Grand Prix.','2010: Vettel takes his first drivers’ world championship here.','2021: A closely contested title season reaches its dramatic conclusion.']},
 'Bahrain in Malaysia':{name:'Sepang International Circuit',opened:'1999 (F1)',wiki:'Sepang_International_Circuit',intro:'Sepang near Kuala Lumpur debuted in Formula 1 in 1999. Its broad corners, long straights and tropical climate made it famous for changeable weather during Malaysian Grands Prix.',moments:['1999: Eddie Irvine wins F1’s first race at Sepang.','The venue hosted Malaysian Grands Prix regularly through 2017.','Any new use of Sepang on the season calendar should be verified with the official schedule.']}
};
// API query uses UTC timestamps so session/race times align without timezone ambiguity.
const V42_WEATHER_SPOTS={
'Australia':[-37.850,144.968],'China':[31.339,121.221],'Japan':[34.843,136.541],
'Bahrain':[26.032,50.510],'Saudi Arabia':[21.633,39.105],'Miami':[25.958,-80.239],
'Canada':[45.504,-73.527],'Monaco':[43.735,7.421],'Barcelona-Catalunya':[41.570,2.262],
'Austria':[47.220,14.764],'Great Britain':[52.073,-1.015],'Belgium':[50.437,5.971],
'Hungary':[47.579,19.249],'Netherlands':[52.388,4.540],'Italy':[45.617,9.281],
'Spain':[40.464,-3.617],'Azerbaijan':[40.372,49.853],'Singapore':[1.291,103.864],
'United States':[30.134,-97.636],'Mexico':[19.405,-99.092],'Brazil':[-23.704,-46.699],
'São Paulo':[-23.704,-46.699],'Las Vegas':[36.114,-115.173],
'Qatar':[25.491,51.454],'Abu Dhabi':[24.467,54.603],
'Bahrain in Malaysia':[2.760,101.738]
};
const V42_WX_MAX_DAYS=16;
const v42ForecastCache=new Map();
const V42_WX_TTL=50*60*1000;
function v42CircuitKey(r){if(V42_CIRCUITS[r.short])return r.short;let n=(r.name||'')+' '+(r.location||'');if(/malaysia|sepang/i.test(n))return 'Bahrain in Malaysia';if(/madrid/i.test(n))return 'Spain';if(/barcelona|montmel/i.test(n))return 'Barcelona-Catalunya';if(/interlagos|s.o paulo/i.test(n))return 'São Paulo';if(/austin/i.test(n))return 'United States';if(/las vegas/i.test(n))return 'Las Vegas';if(/baku/i.test(n))return 'Azerbaijan';if(/silverstone/i.test(n))return 'Great Britain';return r.short;}
function v42Circuit(r){return V42_CIRCUITS[v42CircuitKey(r)]||null;}
function v42Spot(r){return V42_WEATHER_SPOTS[v42CircuitKey(r)];}
function v42WeatherCode(code){if(code==null)return ['—','No forecast'];if(code===0)return ['☀','Clear'];if(code<=2)return ['🌤','Partly cloudy'];if(code===3)return ['☁','Overcast'];if(code===45||code===48)return ['🌫','Fog'];if(code>=51&&code<=67)return ['🌦','Rain or drizzle'];if(code>=71&&code<=77)return ['❄','Snow'];if(code>=80&&code<=82)return ['🌧','Showers'];if(code>=95)return ['⛈','Thunderstorms'];return ['☁','Cloudy'];}
function v42WeatherKey(r){return `${r.round}|${r.race}|${v42CircuitKey(r)}`;}
function v42AgeDays(r){return (new Date(r.race).getTime()-Date.now())/86400000;}
function v42CanForecast(r){return Boolean(v42Spot(r))&&v42AgeDays(r)>=-.5&&v42AgeDays(r)<=V42_WX_MAX_DAYS-1;}
function v42Rounding(v,unit=''){return Number.isFinite(Number(v))?`${Math.round(Number(v))}${unit}`:'—';}
function v42ForecastAt(f,iso){if(!f?.hourly?.time?.length)return null;const target=new Date(iso).getTime();let best=-1,bestDiff=Infinity;for(let i=0;i<f.hourly.time.length;i++){const diff=Math.abs(new Date(f.hourly.time[i]+'Z').getTime()-target);if(diff<bestDiff){best=i;bestDiff=diff;}}if(best<0||bestDiff>65*60000)return null;return {temp:f.hourly.temperature_2m?.[best],rain:f.hourly.precipitation_probability?.[best],wind:f.hourly.wind_speed_10m?.[best],code:f.hourly.weather_code?.[best]};}
function v42RaceSessions(r){const sessions=scheduleFor(r);const find=(pred)=>sessions.find(s=>pred.test(s.name));return [find(/Practice 1/i),find(/^Sprint$/i)||find(/Practice 2/i),find(/^(Sprint )?Qualifying/i),find(/^Race$/i)].filter(Boolean).filter((s,i,a)=>a.indexOf(s)===i);}
function v42WeatherMarkup(r,view='home'){
 const key=v42WeatherKey(r),entry=v42ForecastCache.get(key),days=v42AgeDays(r);
 const head=`<div class="v42-weather-head"><div><span class="v42-kicker">GRAND PRIX WEATHER</span><h3>${safe(r.short)} <span>${v4Flag(r)}</span></h3></div><span class="v42-weather-mark">☀</span></div>`;
 let body='';
 if(!v42Spot(r))body='<p class="v42-weather-message">Circuit location not yet available for a forecast.</p>';
 else if(days < -.5)body='<p class="v42-weather-message">This race has finished. The weather section covers upcoming race weekends only.</p>';
 else if(days > V42_WX_MAX_DAYS-1)body=`<p class="v42-weather-message">The race is still ${Math.ceil(days)} days away. Detailed weather is only shown when the event comes within roughly two weeks.</p><p class="v42-sub">Forecasts will appear automatically nearer the event.</p>`;
 else if(!entry||entry.loading)body='<div class="v42-wx-skeleton">↻ &nbsp; Loading real weather forecasts for the circuit…</div>';
 else if(entry.error)body=`<p class="v42-weather-message">Forecast temporarily unavailable. Check your connection and try again.</p><button type="button" class="v42-weather-retry" data-v42-retry="${r.round}">TRY AGAIN ↻</button>`;
 else {
  const rows=v42RaceSessions(r).map(s=>({s,wx:v42ForecastAt(entry.forecast,s.dateStart)}));
  body=`<div class="v42-weather-grid">${rows.map(({s,wx})=>{const [symbol,label]=v42WeatherCode(wx?.code);return `<div class="v42-weather-day"><div class="v42-weather-session">${safe(s.name)}</div><div class="v42-weather-symbol" aria-hidden="true">${symbol}</div><div class="v42-weather-temp">${wx?v42Rounding(wx.temp,'°C'):'—'}</div><div class="v42-weather-desc">${wx?label:'Too early'}</div><div class="v42-weather-rain">💧 ${wx?v42Rounding(wx.rain,'%'):'—'}</div><small>${fmtDay(s.dateStart)}</small></div>`;}).join('')}</div><div class="v42-weather-bottom"><span>💧 Rain chance · temperatures at session start · wind ${v42Rounding(v42ForecastAt(entry.forecast,r.race)?.wind,' km/h')}</span><span>Updated ${new Intl.DateTimeFormat('en-AU',{timeZone:TZ,hour:'numeric',minute:'2-digit'}).format(new Date(entry.time))} Adelaide</span></div>`;
 }
 return `<section class="v42-weather-panel v42-${view}" data-v42-weather="${r.round}" aria-label="Weather forecast for ${safe(r.name)}">${head}${body}<div class="v42-weather-source">Forecast source: <a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">Open-Meteo</a> · Forecasts change and are not guaranteed · Weather at the circuit, not Adelaide</div></section>`;
}
let v42Fetching=new Set();
async function v42LoadForecast(r,force=false){
 if(!r||!v42CanForecast(r))return;
 const key=v42WeatherKey(r),old=v42ForecastCache.get(key);
 if(v42Fetching.has(key)||(!force&&old?.forecast&&(Date.now()-old.time)<V42_WX_TTL)||(!force&&old?.error&&Date.now()-old.time<2*60*1000))return;
 const [lat,lon]=v42Spot(r);v42Fetching.add(key);v42ForecastCache.set(key,{loading:true,time:Date.now()});
 try{
  const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=temperature_2m,precipitation_probability,weather_code,wind_speed_10m&forecast_days=16&timezone=UTC`;
  const ctrl=new AbortController(),timeout=setTimeout(()=>ctrl.abort(),11000);
  let response;try{response=await fetch(url,{signal:ctrl.signal,mode:'cors'});}finally{clearTimeout(timeout);}
  if(!response.ok)throw Error('Weather HTTP '+response.status);
  const f=await response.json();if(!Array.isArray(f?.hourly?.time)||!f.hourly.time.length)throw Error('Incomplete forecast');
  v42ForecastCache.set(key,{time:Date.now(),forecast:f});
 }catch(e){v42ForecastCache.set(key,{time:Date.now(),error:true});}
 finally{v42Fetching.delete(key);if((st.tab==='home'&&nextRace().round===r.round)||(st.tab==='calendar'&&st.expanded===r.round))render();}
}
function v42QueueWeather(){const r=st.tab==='home'?nextRace():st.tab==='calendar'&&st.expanded!=null?data.races.find(x=>x.round===st.expanded):null;if(r)Promise.resolve().then(()=>v42LoadForecast(r));}
// Make the full track (original schematic or F1 image) open its history, and
// supply a keyboard-accessible button for visitors who prefer explicit controls.
const v42OriginalTrackMarkup=v2TrackMarkup;
v2TrackMarkup=function(r){const h=v42Circuit(r),html=v42OriginalTrackMarkup(r);if(!h)return html;return html+`<div class="v42-history-cta"><button type="button" class="v42-history-button" data-v42-history="${r.round}"><span>◷</span> CIRCUIT HISTORY <span aria-hidden="true">↗</span></button><p>Tap the circuit illustration or outline to explore its story.</p></div>`;};
const v42OldRaceCard=raceCard;
raceCard=function(r){let html=v42OldRaceCard(r);if(st.expanded!==r.round)return html;return html.replace('<div class="raceinner">',`<div class="raceinner">${v42WeatherMarkup(r,'calendar')}`);};
const v42OldHero=v4Hero;
v4Hero=function(){const r=nextRace();return v42OldHero()+v42WeatherMarkup(r,'home');};
const v42OldSettings=v3SettingsPage;
v3SettingsPage=function(){return v42OldSettings().replace('Version 3 · Independent fan app','Version 4.2 · Independent fan app').replace('Version 4 · Independent fan app','Version 4.2 · Independent fan app');};
const v42OldRender=render;
render=function(){v42OldRender();v42QueueWeather();if(st.tab==='home'){const hm=document.querySelector('.v41-hero-map');if(hm){hm.setAttribute('role','button');hm.setAttribute('tabindex','0');hm.setAttribute('aria-label','Open history of the upcoming race circuit');}}if(st.tab==='calendar'&&st.expanded!=null){const r=data.races.find(x=>x.round===st.expanded);if(r){const area=document.querySelector(`#track-${r.round}`);if(area){area.setAttribute('role','button');area.setAttribute('tabindex','0');area.setAttribute('title','Open circuit history');area.setAttribute('aria-label',`Open history of ${v42Circuit(r)?.name||r.location}`);}const img=document.querySelector('.official-circuit .f1-track-art');if(img){img.setAttribute('role','button');img.setAttribute('tabindex','0');img.setAttribute('aria-label','Open circuit history');}}}};
function v42OpenCircuitHistory(r){const h=v42Circuit(r);if(!h)return toast('History not available for this circuit yet');document.querySelector('.v42-history-shade')?.remove();
 const shade=document.createElement('div');shade.className='v42-history-shade';
 const officialUrl=v3F1RaceUrl(r);const wikiUrl='https://en.wikipedia.org/wiki/'+h.wiki;
 shade.innerHTML=`<section class="v42-history-modal" role="dialog" aria-modal="true" aria-labelledby="v42-history-title"><button type="button" class="v42-history-close" data-v42-close aria-label="Close circuit history">×</button><div class="v42-history-illustration"><div class="v42-history-eyebrow">CIRCUIT ARCHIVE · ROUND ${r.round}</div>${v41CircuitSvg(r,'v42-history-circuit')}<small>Illustrative outline · not to scale</small></div><div class="v42-history-content"><span class="v42-history-label">TRACK HISTORY / ${v4Flag(r)}</span><h2 id="v42-history-title">${safe(h.name)}</h2><div class="v42-history-info"><span>🏁 F1 debut / origin: <b>${safe(h.opened)}</b></span><span>📍 ${safe(r.location)}</span></div><p>${safe(h.intro)}</p><h3>Moments that made this circuit</h3><ol class="v42-history-timeline">${h.moments.map(m=>`<li>${safe(m)}</li>`).join('')}</ol><div class="v42-history-links"><a href="${wikiUrl}" target="_blank" rel="noopener noreferrer">CIRCUIT WIKIPEDIA ↗</a><a href="${officialUrl}" target="_blank" rel="noopener noreferrer">OFFICIAL F1 PAGE ↗</a></div><p class="v42-history-note">Brief editorial circuit history · The white outline above is schematic. Source links provide more details.</p></div></section>`;
 document.body.appendChild(shade);shade.querySelector('.v42-history-close')?.focus();}
function v42HistoryRaceFromElement(e){const target=e.closest('[data-v42-history]');if(target)return data.races.find(x=>x.round===Number(target.dataset.v42History));const circuit=e.closest('.official-circuit .f1-track-art, .trackmap');if(circuit&&st.tab==='calendar'&&st.expanded!=null)return data.races.find(x=>x.round===st.expanded);const hero=e.closest('.v41-hero-map');if(hero&&st.tab==='home')return nextRace();return null;}
document.addEventListener('click',e=>{const close=e.target.closest('[data-v42-close]');if(close||e.target.classList?.contains('v42-history-shade')){document.querySelector('.v42-history-shade')?.remove();return;}const retry=e.target.closest('[data-v42-retry]');if(retry){const r=data.races.find(x=>x.round===Number(retry.dataset.v42Retry));if(r)v42LoadForecast(r,true);return;}const r=v42HistoryRaceFromElement(e.target);if(r)v42OpenCircuitHistory(r);});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('.v42-history-shade')?.remove();if((e.key==='Enter'||e.key===' ')&&e.target.matches?.('.trackmap, .official-circuit .f1-track-art, .v41-hero-map')){e.preventDefault();const r=v42HistoryRaceFromElement(e.target);if(r)v42OpenCircuitHistory(r);}});
const v42Header=document.querySelector('.v41-version');if(v42Header)v42Header.textContent='V4.2';
document.title='PITWALL V4.2 — Race Companion';
render();
